name: sample-workflow
on:
  push:
    branches: [develop]
   
jobs:
  job1:
    runs-on: self-hosted
    steps:
    - name: check-out your repository under $GITHUB_WORKSPACE
      uses: actions/checkout@v2
    - name: use echo command
      run: echo "sample-workflow"
